### ISSUE TITLE
Better documentation of code to help utilise code

### ISSUE THREAD

**Issue by ttuti** [ElCasagrande/Udacity-ML-Capstone-Project#3]
Thanks for your project. Really appreciate the effor you've put here. Is it possible to get a breakdown of the logic of the padding sequences function in the DataGenerator class? Its not obvious to me what happens when you have 0 features apart from the correct sequences, skill ids, and user ids compared to when you do.

I keep getting the following error(s) for the following line of code: `x[idx, -len(trunc):] = trunc`

With features:

> could not broadcast input array from shape (21) into shape (21,20)

Without features:

> could not broadcast input array from shape (21) into shape(21,1)

**Comment by lccasagrande** [comment]
I'm not so sure about what do you mean by having 0 features apart...

Could you better explain what are you are trying to do?

**Comment by lccasagrande** [comment]
I've refactored the whole code and migrated to TF-2.0.

Better documentation and tests are now provided.

I believe this issue does not apply anymore. If you have ideas to improve code readability, you can open a pull request or a new issue.
