### ISSUE TITLE
Error in train phase after epoch 1

### ISSUE THREAD

**Issue by KShivendu** [ElCasagrande/Udacity-ML-Capstone-Project#9]
Hi Lucas, Thank you for open sourcing your project. Your code is really clean and easy to understand. But I came across this error while trying to execute it. 

```  
File "examples/run_dkt.py", line 115, in <module>
    run(parse_args())
  File "examples/run_dkt.py", line 46, in run
    tf.keras.callbacks.TensorBoard(log_dir=args.log_dir)
  File "/content/Deep-Knowledge-Tracing/deepkt/deepkt.py", line 141, in fit
    validation_freq=validation_freq)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1133, in fit
    return_dict=True)
TypeError: evaluate() got an unexpected keyword argument 'x'
```
I ran the code on Google colab and got this error after first epoch is over.

To me it seems that this error is because of version mismatch. What version(s) of libraries are required to run it ?

**Comment by KShivendu** [comment]
For GPU `pip install tensorflow-gpu==2.1.0` worked for me. Google colab had `tensorflow-gpu==2.3` as default at the time of this comment.
For CPU, I expect same version or `2.0.0` should work.

**Comment by Mr-ChenSH** [comment]
I have also encountered this problem. How did you solve it

**Comment by Mr-ChenSH** [comment]
modify this class method —— def evaluateq(self,
                 dataset,
                 verbose=1,
                 steps=None,
                 callbacks=None):
